#!/bin/sh

#-----------------------------------------------------------------------------#
# File:     ~/.config/zsh/exportrc  (archlinux - 'silent')
# Date:     Thu 23 Apr 2020 12:06
# Update:   Fri 21 Feb 2025 07:44
# Owner:    fvb - freekvb@gmail.com - https://freekvb.github.io/fvb/
#-----------------------------------------------------------------------------#

#---------- exports - thnx to gotbletu ---------------------------------------#


# {{{ default programs

# DESC: check and choose the first program in the array installed as the default
# find alternative apps if it is installed on your system
find_alt() { for i;do which "$i" >/dev/null &&
    { echo "$i"; return 0; };done;return 1; }

# set the default program
# the first program in the array detected on your system will be the default

export OPENER=$(find_alt xdg-open)

export BROWSER=$(find_alt zen-browser firefox qutebrowser chromium $OPENER)
export BROWSERCLI=$(find_alt lynx w3m $OPENER )
#export BROWSERTOR=$(find_alt tor-browser-en)
export DIFFPROG="nvim -d"
export EDITOR=$(find_alt nvim vim helix $OPENER)
#export FILEMANAGER=$(find_alt nemo $OPENER)
export FILEMANAGERCLI=$(find_alt lf vifm ranger $OPENER)
export IMAGEVIEWER=$(find_alt feh nsxiv $OPENER)
export MANPAGER="nvim +Man!"
export MUSICER=$(find_alt moc mpv $OPENER)
export PAGER=$(find_alt less more most)
export PLAYER=$(find_alt mpv mplayer ffplay $OPENER)
export READER=$(find_alt zathura $OPENER)
export TERM=$(find_alt foot st xterm $OPENER)
export VISUAL=$EDITOR
#export WORDPROCESSOR=$(find_alt wordgrinder $OPENER )

# }}}

# {{{ XDG paths

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_BIN_HOME=$HOME/.local/bin
export XDG_LIB_HOME=$HOME/.local/lib
export XDG_TMP_HOME=$HOME/.local/tmp

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc":"$XDG_CONFIG_HOME/gtk-2.0/gtkrc.mine"
export LYNX_CFG="$XDG_CONFIG_HOME/lynx/lynx.cfg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass/password-store"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# }}}

# {{{ paths

if [[ ! "$PATH" == */bin* ]]; then
  export PATH="${PATH:+${PATH}:}/bin"
fi

if [[ ! "$PATH" == */home/fvb/.local/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.local/bin"
fi

if [[ ! "$PATH" == */home/fvb/.local/share/go/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.local/share/go/bin"
fi

if [[ ! "$PATH" == */home/fvb/Scripts* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/Scripts"
fi

if [[ ! "$PATH" == */home/fvb/.local/share/gem/ruby/3.0.0/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.local/share/gem/ruby/3.0.0/bin"
fi

if [[ ! "$PATH" == */home/fvb/.local/share/cargo/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.local/share/cargo/bin"
fi

if [[ ! "$PATH" == */home/fvb/.fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.fzf/bin"
fi


# }}}

