#!/bin/sh

#-----------------------------------------------------------------------------#
# File:     ~/.config/zsh/exportrc  (archlinux - 'silent')
# Date:     Thu 23 Apr 2020 12:06
# Update:   Thu 14 Oct 2021 17:09
# Owner:    fvb - freekvb@gmail.com - https://freekvb.github.io/fvb/
#-----------------------------------------------------------------------------#

#---------- exports - thnx to gotbletu ---------------------------------------#


#{{{ default programs

# DESC: check and choose the first program in the array installed as the default
# find alternative apps if it is installed on your system
find_alt() { for i;do which "$i" >/dev/null &&
    { echo "$i"; return 0;};done;return 1; }

# set the default program
# the first program in the array detected on your system will be the default

export OPENER=$(find_alt xdg-open)

export BROWSER=$(find_alt qutebrowser chromium $OPENER)
export BROWSERCLI=$(find_alt lynx w3m links2 links elinks $OPENER )
#export BROWSERTOR=$(find_alt tor-browser-en)
export EDITOR=$(find_alt nvim vim vi nano $OPENER)
#export FILEMANAGER=$(find_alt nemo $OPENER)
export FILEMANAGERCLI=$(find_alt vifm ranger lf $OPENER)
export IMAGEVIEWER=$(find_alt feh sxiv $OPENER)
export MANPAGER="nvim +Man!"
export MUSICER=$(find_alt moc mpv $OPENER)
export PAGER=$(find_alt less more most)
export PLAYER=$(find_alt mpv mplayer ffplay $OPENER)
export READER=$(find_alt zathura apvlv mupdf evince $OPENER)
export TERM=$(find_alt st urxvt xterm uxterm termite terminology $OPENER)
#export WORDPROCESSOR=$(find_alt wordgrinder $OPENER )

#}}}

#{{{ XDG paths

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export GNUPGHOME="$XDG_DATA_HOME/gnupg/"
export GOPATH="$XDG_DATA_HOME/go"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export YTFZF_CONFIG_DIR=$HOME/.config/ytfzf

#}}}

#{{{ paths

if [[ ! "$PATH" == */bin* ]]; then
  export PATH="${PATH:+${PATH}:}/bin"
fi

if [[ ! "$PATH" == */home/fvb/.local/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.local/bin"
fi

if [[ ! "$PATH" == */home/fvb/.local/share/go/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.local/share/go/bin"
fi

if [[ ! "$PATH" == */home/fvb/Scripts* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/Scripts"
fi

if [[ ! "$PATH" == */home/fvb/.gem/ruby/2.7.0/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.gem/ruby/2.7.0/bin"
fi

if [[ ! "$PATH" == */home/fvb/.cargo/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.cargo/bin"
fi

if [[ ! "$PATH" == */home/fvb/.fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.fzf/bin"
fi

if [[ ! "$PATH" == */home/fvb/.config/bspwm* ]]; then
  export PATH="${PATH:+${PATH}:}/home/fvb/.config/bspwm"
fi

if [[ ! "$PATH" == */usr/lib/surfraw* ]]; then
  export PATH="${PATH:+${PATH}:}/usr/lib/surfraw"
fi

#}}}

