#!/bin/sh

#-----------------------------------------------------------------------------#
# File:     ~/.config/sxhkd/sxhkdrc (archlinux @ 'silent')
# Date:     Thu 23 Apr 2020 12:09
# Update:   Sat 13 May 2023 01:36
# Owner:    fvb - freekvb@gmail.com - https://freekvb.github.io/fvb/
#-----------------------------------------------------------------------------#


#
# wm independent hotkeys
#

# terminal emulator
alt + space
    st

# program launcher
super + Return
    dmenu_run

# tdrop terminal
super + d
    tdrop -m -w 1916 -a st

# clipboard manager
alt + p
    clipmenu -i

# emojis to clipboard
super + e
    ./Scripts/dmenu-emoji

# lock screen
alt + z
    xset dpms force off

# control sound volume
super + {comma,period,slash}
    amixer -q set Master {5%- unmute,5%+ unmute,toggle}
#    pamixer --allow-boost {-d 5,-i 5,-t}

# toggle pause/play moc
alt + x
    mocp -G

# qutebrowser
super + q
    qutebrowser

# firefox
super + f
firefox

# chromium
super + c
    chromium

# mt5
super + m
mt5

# youtube pipecat
alt + y
    pipecat-turbo.sh

# date time notification
super + d
    dunstify $(date +'%R')

# firefox / chromium  - youtube (link yanked) in mpv
alt + v
    ./Scripts/yt_mpv

# trade screenshots
super + x
    scrot '%d-%b-%Y-%H:%M:%S.png' -e 'mv $f ~/Notes/trades/tp' && dunstify "chart screenshot  >>  trades/tp"

# review screenshots
super + s
    scrot '%d-%b-%Y-%H:%M.png' -e 'mv $f ~/Notes/trade/reviews/' && dunstify "chart screenshot  >>  trades/reviews"



#
# sxhkd
#

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd; dunstify 'sxhkd: config reloaded'



#
# bspwm hotkeys
#

# restart bspwm
super + shift + r
    bspc wm -r; dunstify 'bspwm: config reloaded'

# quit bspwm
super + shift + q
    bspc quit

# toggle top padding for lemonbar
alt + shift + {p,n}
    bspc config top_padding {16,1}

# toggle gaps
alt + shift + {g,h,o}
    bspc config window_gap {8,4,0}

# alternate between the tiled and monocle layout
alt + m
    bspc desktop -l next

# close one or all nodes
super + {_,shift + }w
    bspc node -{c,k}


#
# state/flags
#

# set the window state
alt + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}


#
# focus/swap
#

# focus or swap the node in the given direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# focus the next/previous desktop in the current monitor
alt + {j,k}
    bspc desktop -f {prev,next}.local

# focus the next/previous occupied desktop in the current monitor
alt + {h,l}
    bspc desktop -f {prev.occupied,next.occupied}.local

# focus the last node/desktop
super + Tab
    bspc desktop -f last

# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# rotate node tree
alt + ctrl + {comma,period}
    bspc node @/ -C {backward,forward}

# rotate layout
alt + shift + {comma,period}
    bspc node @/ --rotate -90


#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
    bspc node -p {west,south,north,east}

# cancel the preselection for the focused node
alt + ctrl + @space
    bspc node -p cancel


#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}

