# Shell variables
# Generated by 'wal'
wallpaper='/home/fvb/Pictures/wallpapers/japanese_girl_right.jpg'

# Special
background='#0c0a0a'
foreground='#e8e3de'
cursor='#e8e3de'

# Colors
color0='#0c0a0a'
color1='#7F8279'
color2='#8F8678'
color3='#ADA293'
color4='#C6B9AA'
color5='#D3C5B8'
color6='#DDD3C8'
color7='#e8e3de'
color8='#a29e9b'
color9='#7F8279'
color10='#8F8678'
color11='#ADA293'
color12='#C6B9AA'
color13='#D3C5B8'
color14='#DDD3C8'
color15='#e8e3de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
