--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fvb/Pictures/wallpapers/scream_cropped.jpg"

-- Special
background="#0d0d0d"
foreground="#c2c2c2"
cursor="#c2c2c2"

-- Colors
color0="#0d0d0d"
color1="#6c6c6b"
color2="#787875"
color3="#848483"
color4="#90918d"
color5="#a2a3a2"
color6="#a7a8a5"
color7="#978c8c"
color8="#6a5757"
color9="#91918F"
color10="#A1A19D"
color11="#B1B1AF"
color12="#C1C2BD"
color13="#D9DAD9"
color14="#DFE0DC"
color15="#c2c2c2"
