--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fvb/Pictures/wallpapers/japanese_girl_right.jpg"

-- Special
background="#0c0a0a"
foreground="#e8e3de"
cursor="#e8e3de"

-- Colors
color0="#0c0a0a"
color1="#7F8279"
color2="#8F8678"
color3="#ADA293"
color4="#C6B9AA"
color5="#D3C5B8"
color6="#DDD3C8"
color7="#e8e3de"
color8="#a29e9b"
color9="#7F8279"
color10="#8F8678"
color11="#ADA293"
color12="#C6B9AA"
color13="#D3C5B8"
color14="#DDD3C8"
color15="#e8e3de"
