[colors.primary]
background = "#0d0d0d"
foreground = "#c2c2c2"

[colors.cursor]
text = "#0d0d0d"
cursor = "#c2c2c2"

[colors.vi_mode_cursor]
text = "#0d0d0d"
cursor = "#c2c2c2"

[colors.search.matches]
foreground = "#0d0d0d"
background = "#c2c2c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a5757"
background = "#978c8c"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d0d0d"
red = "#6c6c6b"
green = "#787875"
yellow = "#848483"
blue = "#90918d"
magenta = "#a2a3a2"
cyan = "#a7a8a5"
white = "#978c8c"

[colors.bright]
black = "#6a5757"
red = "#91918F"
green = "#A1A19D"
yellow = "#B1B1AF"
blue = "#C1C2BD"
magenta = "#D9DAD9"
cyan = "#DFE0DC"
white = "#c2c2c2"

[colors.dim]
black = "#c2c2c2"
red = "#91918F"
green = "#D9DAD9"
yellow = "#B1B1AF"
blue = "#C1C2BD"
magenta = "#A1A19D"
cyan = "#DFE0DC"
white = "#6a5757"

