# Shell variables
# Generated by 'wal'
wallpaper="/home/fvb/Pictures/wallpapers/scream_cropped.jpg"

# Special
background='#0d0d0d'
foreground='#c2c2c2'
cursor='#c2c2c2'

# Colors
color0='#0d0d0d'
color1='#6c6c6b'
color2='#787875'
color3='#848483'
color4='#90918d'
color5='#a2a3a2'
color6='#a7a8a5'
color7='#978c8c'
color8='#6a5757'
color9='#91918F'
color10='#A1A19D'
color11='#B1B1AF'
color12='#C1C2BD'
color13='#D9DAD9'
color14='#DFE0DC'
color15='#c2c2c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
