--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fvb/Pictures/wallpapers/japanese_girl_right.jpg"

-- Special
background="#0c0a0a"
foreground="#c2c1c1"
cursor="#c2c1c1"

-- Colors
color0="#0c0a0a"
color1="#635b51"
color2="#6b645a"
color3="#81786e"
color4="#948a7f"
color5="#9e9389"
color6="#a59d96"
color7="#968a8a"
color8="#695656"
color9="#847A6C"
color10="#8F8678"
color11="#ACA193"
color12="#C6B9AA"
color13="#D3C5B7"
color14="#DCD2C8"
color15="#c2c1c1"
