#!/bin/sh

#-----------------------------------------------------------------------------#
# File:     ~/.config/bspwm/bspwmrc (archlinux @ 'silent')
# Date:     Thu 23 Apr 2020 12:07
# Owner:    fvb - freekvb@gmail.com - https://freekvb.github.io/fvb/
#-----------------------------------------------------------------------------#


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            1
bspc config window_gap              4
bspc config top_padding             1
bspc config right_padding           0
bspc config bottom_padding          0
bspc config left_padding            1

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color     "$color1"
bspc config active_border_color     "$color2"
bspc config focused_border_color    "$color3"
bspc config presel_feedback_color   "$color1"

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config presel_feedback_color   '#555555'

bspc config automatic_scheme        spiral
bspc config initial_polarity        first_child

bspc rule -a apvlv                  state=tiled
bspc rule -a mpv -name "video0"     state=floating
bspc rule -a guvcview               state=floating rectangle=480x270+1428+798 sticky=on layer=above
bspc rule -a Zathura                state=tiled


wal -R

~/.fehbg &
