#!/bin/sh

# check how many packages to update and mails to read

echo "pacs to update:  " $(checkupdates | wc -l) &&
echo "mails to read:   " $(curl -u freekvb:tmkehqqsioigwxif --silent "https://mail.google.com/mail/feed/atom" | tr -d '\n' | awk -F '<entry>' '{for (i=2; i<=NF; i++) {print $i}}' | sed -n "s/<title>\(.*\)<\/title.*name>\(.*\)<\/name>.*/\2 - \1/p" | wc -l)

