#!/bin/sh

set -e

case "$1" in
  "list")
    data=$(sed '0,/^__DATA__$/d' "$0")
    echo "$data"
    ;;
  "copy")
    input=$(tee)
    if [ ! -z "$input" ]; then
      emoji=${input: -1}
      echo -n "$emoji" | xclip -i -selection c
      command -v notify-send > /dev/null && notify-send -t 1000 "$emoji copied!"
    fi
    ;;
  "")
    bash $0 list | dmenu -p 'emoji: ' | bash $0 wl-copy
    ;;
esac

exit

__DATA__
grinning face                                   😀
smiling face with open mouth                    😃
smiling face with open mouth & smiling eyes     😄
grinning face with smiling eyes                 😁
smiling face with open mouth & closed eyes      😆
smiling face with open mouth & cold sweat       😅
face with tears of joy                          😂
rolling on the floor laughing                   🤣
smiling face with smiling eyes                  😊
smiling face with halo                          😇
slightly smiling face                           🙂
upside-down face                                🙃
winking face                                    😉
relieved face                                   😌
smiling face with heart-eyes                    😍
face blowing a kiss                             😘
kissing face                                    😗
kissing face with smiling eyes                  😙
kissing face with closed eyes                   😚
face savouring delicious food                   😋
face with stuck-out tongue & winking eye        😜
face with stuck-out tongue & closed eyes        😝
face with stuck-out tongue                      😛
money-mouth face                                🤑
hugging face                                    🤗
nerd face                                       🤓
smiling face with sunglasses                    😎
clown face                                      🤡
cowboy hat face                                 🤠
smirking face                                   😏
unamused face                                   😒
disappointed face                               😞
pensive face                                    😔
worried face                                    😟
confused face                                   😕
slightly frowning face                          🙁
frowning face                                   ☹️
persevering face                                😣
confounded face                                 😖
tired face                                      😫
weary face                                      😩
face with steam from nose                       😤
angry face                                      😠
pouting face                                    😡
face without mouth                              😶
neutral face                                    😐
expressionless face                             😑
hushed face                                     😯
frowning face with open mouth                   😦
anguished face                                  😧
face with open mouth                            😮
astonished face                                 😲
dizzy face                                      😵
flushed face                                    😳
face screaming in fear                          😱
fearful face                                    😨
face with open mouth & cold sweat               😰
crying face                                     😢
disappointed but relieved face                  😥
drooling face                                   🤤
loudly crying face                              😭
face with cold sweat                            😓
sleepy face                                     😪
sleeping face                                   😴
face with rolling eyes                          🙄
thinking face                                   🤔
lying face                                      🤥
grimacing face                                  😬
zipper-mouth face                               🤐
nauseated face                                  🤢
sneezing face                                   🤧
face with medical mask                          😷
face with thermometer                           🤒
face with head-bandage                          🤕
smiling face with horns                         😈
angry face with horns                           👿
ogre                                            👹
goblin                                          👺
pile of poo                                     💩
ghost                                           👻
skull                                           💀
skull and crossbones                            ☠️
alien                                           👽
alien monster                                   👾
robot face                                      🤖
thumbs up                                       👍
thumbs down                                     👎
crossed fingers                                 🤞
victory hand                                   ✌️
raised hand                                     ✋
waving hand                                     👋
call me hand                                    🤙
middle finger                                   🖕
kiss mark                                       💋
eyes                                            👀
red heart                                       ❤️
broken heart                                    💔
dollar banknote                                 💵
euro banknote                                   💶

