#!/bin/sh

lynxpath=/usr/bin/lynx
useragent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Lynx"

if [ -e "$HOME/.config/lynx/lynx.cfg" ];then
  export LYNX_CFG="$HOME/.config/lynx/lynx.cfg"
fi

if [ -e "$HOME/.config/lynx/lynx.lss" ];then
  export LYNX_LSS="$HOME/.config/lynx/lynx.lss"
fi

if [ ! -x "$lynxpath" ]; then
  echo "Doesn't look like lynx is installed."
  exit 1
fi

exec "$lynxpath" --useragent="$useragent" "$@"

