#!/usr/bin/bash

# copy last given (n) lynx bookmarks
# and paste them in markdown format

count=1
if test -n "$1"; then
    count="$1"
fi

IFS=$'\n'
html=($(tail -"${count}" ~/.config/lynx/lynx_bookmarks.html | pandoc -f html -t markdown --wrap=none))

for line in ${html[@]}; do
   [[ $line =~ ^\[(.+)\]\((.+)\) ]]
   echo "* [${BASH_REMATCH[1]}] <${BASH_REMATCH[2]}>"
   echo ""
done
