#!/usr/bin/bash

# copy last given (n) lynx bookmarks
# and run thru rdrview

IFS=$'\n'
html=($(tail -1 ~/.config/lynx/lynx_bookmarks.html | pandoc -f html -t markdown --wrap=none))

for line in ${html[@]}; do
   [[ $line =~ ^\[(.+)\]\((.+)\) ]]
   rdrview -H "${BASH_REMATCH[2]}" | lynx -stdin
   head -n -1 ~/.config/lynx/lynx_bookmarks.html > tmp.html && mv tmp.html ~/.config/lynx/lynx_bookmarks.html
done

