#!/usr/bin/sh

# show in terminal what mails in gmail inbox

curl -u freekvb:tmkehqqsioigwxif --silent "https://mail.google.com/mail/feed/atom" | tr -d '\n' | awk -F '<entry>' '{for (i=2; i<=NF; i++) {print $i}}' | sed -n "s/<title>\(.*\)<\/title.*name>\(.*\)<\/name>.*/\2  -  \1/p"


