#!/bin/sh

# pars - paru (yay) fzf install given aur pkg

#yay -Slq | fzf --multi --preview 'yay -Si {1}' --preview-window "right:50%" --prompt "install aur pkg: " | xargs -ro yay -S
paru -Slq | fzf --multi --preview 'paru -Si {1}' --preview-window "right:50%" --prompt "install aur pkg: " | xargs -ro paru -S

