#!/bin/sh

# save new gnote in $HOME/Notes/.gnotes as 'timestamp__title.md'
# publish on github with title as commit


title=$(awk 'NR==1{$1=""; print }' "$HOME"/Notes/.new_note.md)

newfile=$(date +%Y%m%d-%H:%M\ )-$title

mv "$HOME"/Notes/.new_note.md "$HOME/Notes/.gnotes/$newfile".md

dir=$(pwd)

cd "$HOME"/Notes/.gnotes || exit

git add .
git commit -m "$title"
git push -q

cd "$dir" || exit

dunstify "gnote saved and published"
