#!/usr/bin/sh

# no dwm bar
# snapshot system in terminal

echo "cpu  :" $(top -bn 1 | awk '/^%Cpu/ { print int($2 + $4 + $6)"%" }') &&
echo "temp :" $(sensors | awk '/^Package/ { print $4+0"°C" }') &&
echo "load :" $(cat /proc/loadavg | awk '{ print $1, $2, $3 }') &&
echo "mem  :" $(free -h | awk '/^Mem/ { print $3"/"$2 }' | sed s/i//g) &&
echo "root :" $(df -hl / | awk '{ print $5 }' | tail -n 1) &&
echo "home :" $(df -hl /home | awk '{ print $5 }' | tail -n 1)

