#!/bin/sh

# set wallpaper and set picture in fastfetch [fetch]

WALLPAPER_DIR="$HOME/Pictures/wallpapers/"
CURRENT_WALL=$(hyprctl hyprpaper listloaded)

# get a random wallpaper that is not the current one
#WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# select wallpaper
WALLPAPER="$f"

# apply the selected wallpaper
hyprctl hyprpaper reload ,"$WALLPAPER"

# set wallpaper in 'fast'fetch
fastfetch --logo "$WALLPAPER" --logo-type sixel --logo-width 50 --logo-height 19 --logo-padding-top 1

# load new wallpaper [cover = default] in hyprpaper.conf
printf "preload = %s\n" $WALLPAPER > $HOME/.config/hypr/hyprpaper.conf
printf "wallpaper = , %s\n" $WALLPAPER >> $HOME/.config/hypr/hyprpaper.conf


