#!/bin/sh

# dwm
# wpgtk auto select wallpaper from directory, set background and colorscheme
# compile and restart dwm

echo "chosing wallpaper for color scheme ... "
wall=$(find $HOME/Pictures/wallpapers | shuf -n 1)
echo "setting wallpaper background ... "
feh --no-fehbg --bg-fill $wall
echo "setting color scheme ... "
wal -i $wall
echo "compiling dwm and dmenu with color scheme ... "
cd $HOME/Programs/dwm && rm -f config.h && doas make clean install
echo "compiling dmenu with color scheme ... "
cd $HOME/Programs/dmenu && rm -f config.h && doas make clean install
echo "restarting dwm "
xdotool key super+shift+q
