#!/usr/bin/sh

# publish new zettel note on github and copy to ~/Notes/zettels/

cd ~/Notes/zet || return

file=$(git status | awk 'NR == 6 {print $1}')
title=$(awk 'NR == 1' "$file" )
newfile=$(git status | awk 'NR == 6 {print $1}' | cut -c -17)

git add "$file" &&
git commit -m "$title" &&
git push &&

cp "$file" ~/Notes/zettels/"$newfile"_"$title".md

dunstify "zettel published and copied"

cd .. || return
rm -f new.md

cd ~ || return

