#-----------------------------------------------------------------------------#
# File:     ~/.config/nimdow/config.toml (archlinux @ 'silent')
# Date:     Sat 12 May 2023 01:40
# Update:   Mon 08 Jul 2024 22:12
# Owner:    fvb - freekvb@gmail.com - https://freekvb.github.io/fvb/
#-----------------------------------------------------------------------------#


# App Rules
# Example:
# [[appRule]]
# class = "st"
# instance = "st"
# title = "st"
# monitor = 1
# tags = [ 1, 4, 7 ]
# state = "floating" # normal, floating, and fullscreen are all valid.

# Start external programs
[[startProcess]]
command = "pkill nimdow"
keys = [ "q" ]
modifiers = [ "shift", "super" ]

[[startProcess]]
command = "st"
keys = [ "@space" ]
modifiers = [ "alt" ]

[[startProcess]]
command = "dmenu_run"
keys = [ "Return" ]
modifiers = [ "super" ]

[[startProcess]]
command = "qutebrowser"
keys = [ "q" ]
modifiers = [ "super" ]

[[startProcess]]
command = "firefox"
keys = [ "f" ]
modifiers = [ "super" ]

[[startProcess]]
command = "chromium"
keys = [ "c" ]
modifiers = [ "super" ]

[[startProcess]]
command = "mt5"
keys = [ "m" ]
modifiers = [ "super" ]

[[startProcess]]
command = "clipmenu -i"
keys = [ "p" ]
modifiers = [ "alt" ]

[[startProcess]]
command = "pamixer --allow-boost -d 5 && notify-send --hint=string:x-dunst-stack-tag:volume: $(vol)"
keys = [ "comma" ]
modifiers = [ "super" ]

[[startProcess]]
command = "pamixer --allow-boost -i 5 && notify-send --hint=string:x-dunst-stack-tag:volume: $(vol)"
keys = [ "period" ]
modifiers = [ "super" ]

[[startProcess]]
command = "pamixer -t"
keys = [ "slash" ]
modifiers = [ "super" ]

[[startProcess]]
command = "mocp -M $XDG_CONFIG_HOME/moc -G"
keys = [ "x" ]
modifiers = [ "alt" ]

[[startProcess]]
command = "xset dpms force off"
keys = [ "z" ]
modifiers = [ "alt" ]

[[startProcess]]
command = "pmenu"
keys = [ "p" ]
modifiers = [ "super" ]

[[startProcess]]
command = "scrot '%d-%b-%Y-%H:%M:%S.png' -e 'mv $f ~/Notes/trades/tp/' && dunstify 'chart screenshot  >>  trades/tp'"
keys = [ "x" ]
modifiers = [ "super" ]

# Example: Start process when region is clicked, see github wiki for what constitutes a region
# [[startProcess]]
# command = "notify-send \"Id: %1, rx: %2, cx: %4, w: %6\""
# clickRegion = 0

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  #"firefox",
  #"st",
]

[settings]
  # Window settings
  borderWidth = 1
  borderColorUnfocused = "#282a36"
  borderColorFocused = "#E0C9B6"
  borderColorUrgent = "#ff5555"
  # Bar settings
  barHeight = 20
  windowTitlePosition = "left"
  barBackgroundColor = "#282a36"
  barForegroundColor = "#f8f8f2"
  barSelectionColor = "#E0C9B6"
  barUrgentColor = "#ff5555"
  barFonts = [
    "Hack:size=10:antialias=true",
    "NotoColorEmoji:size=10:antialias=true"
  ]
  # Layout settings
  gapSize = 0
  outerGap = 0
  resizeStep = 10
  # Scratchpad settings
  scratchpadWidth = 500
  scratchpadHeight = 300
  # General settings
  loggingEnabled = false
  reverseTagScrolling = false
  # The key used for moving and resizing windows.
  # All options: "control", "shift", "alt", "alt", "caps lock", "mod1", "mod2", "mod3", "mod4", "mod5"
  # alt is an alias for Mod1Mask,
  # alt is an alias for Mod4Mask
  # See keyutils.nim for details
  modKey = "alt"

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "alt" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "alt" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "alt", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "alt", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "alt" ]

  [controls.destroySelectedWindow]
  keys = [ "w" ]
  modifiers = [ "super" ]

#  [controls.goToPreviousTag]
#  keys = [ "w" ]
#  modifiers = [ "alt" ]
#
#  [controls.moveWindowToPreviousTag]
#  keys = [ "w" ]
#  modifiers = [ "alt", "shift" ]
#
#  [controls.focusPreviousMonitor]
#  keys = [ "comma" ]
#  modifiers = [ "alt" ]
#
#  [controls.focusNextMonitor]
#  keys = [ "period" ]
#  modifiers = [ "alt" ]
#
#  [controls.moveWindowToPreviousMonitor]
#  keys = [ "comma" ]
#  modifiers = [ "alt", "shift" ]
#
#  [controls.moveWindowToNextMonitor]
#  keys = [ "period" ]
#  modifiers = [ "alt", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "l" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "h" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "f" ]
  modifiers = [ "alt", "shift" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "alt" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt" ]

  [controls.goToLeftTag]
  keys = [ "h" ]
  modifiers = [ "alt" ]

  [controls.goToRightTag]
  keys = [ "l" ]
  modifiers = [ "alt" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt", "shift" ]

  [controls.moveWindowToLeftTag]
  keys = [ "Left" ]
  modifiers = [ "alt" ]

  [controls.moveWindowToRightTag]
  keys = [ "Right" ]
  modifiers = [ "alt" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt", "shift", "control" ]

  [controls.increaseMasterWidth]
  keys = [ "l" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterWidth]
  keys = [ "h" ]
  modifiers = [ "super" ]

  [controls.moveWindowToScratchpad]
  keys = [ "s" ]
  modifiers = [ "alt", "shift" ]

  [controls.popScratchpad]
  keys = [ "s" ]
  modifiers = [ "alt" ]

  [controls.rotateClients]
  keys = [ "r" ]
  modifiers = [ "alt" ]

  [controls.toggleStatusBar]
  keys = [ "b" ]
  modifiers = [ "alt" ]

# Example monitor settings:
# [monitors]
  # [monitors.default.tags]
  # 1.displayString = "one"
  # 2.displayString = "foobar"
  # Set the number of master windows for ALL monitors.
  # all.numMasterWindows = 2
  # all.defaultMasterWidthPercentage = 60

  # [monitors.1.tags]
  # 2.displayString = "two"
  # Set the number of master windows per-monitor.
  # all.numMasterWindows = 3
  # Set the number of master windows per-tag.
  # 2.numMasterWindows = 1

  # [monitors.2.tags]
  # 2.displayString = "too"

